### ISSUE TITLE
Don't work with some relations

### ISSUE THREAD

**Issue by g-rodigy** [la-haute-societe/yii2-save-relations-behavior#60]
Migration
````
 $this->createTable('{{%project}}', [
            'id' => $this->primaryKey(),
            'name' => $this->string(32)->notNull(),
        ]);
 $this->createTable('{{%project_company}}', [
            'id' => $this->primaryKey(),
            'project_id' => $this->integer()->notNull(),
            'title' => $this->string(64)->notNull(),
            'desc' => $this->text()->notNull(),
        ]);
````

Model
````php
use lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior;

class Project extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            'saveRelations' => [
                'class'     => SaveRelationsBehavior::className(),
                'relations' => [ 'company'],
            ],
        ];
    }

    public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL,
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getCompany()
    {
        return $this->hasOne(ProjectCompany::className(), ['project_id' => 'id']);
    }

   // other relations
}
````

This code don't work, because project_id don't set automatically
````php
$project = Project::findOne(1);
$project->company = ['title' => 'new company']; 
$project->save();
````

**Comment by artemryzhov** [comment]
I have the same issue.

This code does not work:

```js
fetch('/api/v1/user/1', {
	method: 'PATCH',
	headers: {'Content-Type': 'application/json'},
	body: JSON.stringify({UserInfo: {phone_verified: false}})
})
```

But this works fine (when id of UserInfo is passed):

```js
fetch('/api/v1/user/1', {
	method: 'PATCH',
	headers: {'Content-Type': 'application/json'},
	body: JSON.stringify({UserInfo: {id: 1, phone_verified: false}})
})
```

Possible solution is change _loadOrCreateRelationModel function:

```php
private function _loadOrCreateRelationModel($data, $fks, $modelClass, $relationName)
{
    /** @var BaseActiveRecord $relationModel */
    $relationModel = null;
    if ($this->owner->$relationName instanceof $modelClass) {
        $relationModel = $this->owner->$relationName;
    }
    if (!$relationModel) {
        if (!empty($fks)) {
            $relationModel = $modelClass::findOne($fks);
        }
        if (!($relationModel instanceof BaseActiveRecord) && !empty($data)) {
            $relationModel = new $modelClass;
        }
    }
    // If a custom scenario is set, apply it here to correctly be able to set the model attributes
    if (array_key_exists($relationName, $this->_relationsScenario)) {
        $relationModel->setScenario($this->_relationsScenario[$relationName]);
    }
    if (($relationModel instanceof BaseActiveRecord) && is_array($data)) {
        $relationModel->setAttributes($data);
        if ($relationModel->hasMethod('loadRelations')) {
            $relationModel->loadRelations($data);
        }

    }
    return $relationModel;
}
```

It tries to load relation from the owner model.

@malinink, can you check is it correct, please?

**Comment by malinink** [comment]
@artemryzhov @g-rodigy 
It seems that library does not support one to one reverse relation.
And just using direct relation will solve the deal well.
Is there any strong need of supporting reverse relation?

**Comment by malinink** [comment]
@artemryzhov You current solution breaks some test, need to check more deeper.

**Comment by juban** [comment]
@artemryzhov @g-rodigy 
I think there is a misunderstanding on how the relations should be created or updated by the behavior.
If an existing relation should be updated, you should provide its id (or primary keys) otherwise a new related record will be created.
This is the intended behavior because we should have a way to create new relations as well as update existing one.

**Comment by g-rodigy** [comment]
@juban 
> I think there is a misunderstanding on how the relations should be created or updated by the behavior.
> If an existing relation should be updated, you should provide its id (or primary keys) otherwise a new related record will be created.

In my case, I expect a new record will be created, what wrong?
````
yii\base\InvalidCallException: Unable to link models: the primary key of frontend\Project is null. in ...\vendor\yiisoft\yii2\db\BaseActiveRecord.php:1572
Stack trace:
#0 ...\vendor\yiisoft\yii2\db\BaseActiveRecord.php(1350): yii\db\BaseActiveRecord->bindModels(Array, Object(frontend\ProjectCompany), Object(frontend\Project))
#1 ...\vendor\la-haute-societe\yii2-save-relations-behavior\src\SaveRelationsBehavior.php(666): yii\db\BaseActiveRecord->link('company', Object(frontend\ProjectCompany))
#2 ...\vendor\la-haute-societe\yii2-save-relations-behavior\src\SaveRelationsBehavior.php(514): lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior->_afterSaveHasOneRelation('company')
#3 [internal function]: lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior->afterSave(Object(yii\db\AfterSaveEvent))
#4 ...\vendor\yiisoft\yii2\base\Component.php(628): call_user_func(Array, Object(yii\db\AfterSaveEvent))
#5 ...\vendor\yiisoft\yii2\db\BaseActiveRecord.php(1000): yii\base\Component->trigger('afterUpdate', Object(yii\db\AfterSaveEvent))
#6 ...\vendor\yiisoft\yii2\db\BaseActiveRecord.php(825): yii\db\BaseActiveRecord->afterSave(false, Array)
#7 ...\vendor\yiisoft\yii2\db\ActiveRecord.php(681): yii\db\BaseActiveRecord->updateInternal(NULL)
#8 ...\vendor\yiisoft\yii2\db\BaseActiveRecord.php(681): yii\db\ActiveRecord->update(true, NULL)
#9 ...\app\frontend\controllers\SiteController.php(147): yii\db\BaseActiveRecord->save()
#10 [internal function]: frontend\controllers\SiteController->actionTest()
#11 ...\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#12 ...\vendor\yiisoft\yii2\base\Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 ...\vendor\yiisoft\yii2\base\Module.php(534): yii\base\Controller->runAction('test', Array)
#14 ...\vendor\yiisoft\yii2\web\Application.php(104): yii\base\Module->runAction('site/test', Array)
#15 ...\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#16 ...\app\frontend\web\index.php(17): yii\base\Application->run()
#17 {main}
````
